### ISSUE TITLE
Incorrect k8gb chart metadata in ArtifactHub

### ISSUE THREAD

**Issue by somaritane** [k8gb-io/k8gb#1034]
1. AbsaOSS is listed as an org, k8gb.io should be there
2. Version information is provided for the previous release, not the current one

![image](https://user-images.githubusercontent.com/502695/204255597-5bd7eec4-9b0b-4798-9983-638d1a9970aa.png)

**Comment by ytsarev** [comment]
Should be fixed with next release assuming we follow extended release instructions https://github.com/k8gb-io/k8gb/pull/1639
