### ISSUE TITLE
Create sample Grafana dashboard reflecting K8GB metrics

### ISSUE THREAD

**Issue by somaritane** [k8gb-io/k8gb#120]
As followup to  
https://github.com/AbsaOSS/ohmyglb/pull/97#issuecomment-618336224,
let's create sample Graphana dashboard showing off exposed prometheus metrics.
Dashboard can be uploaded with some sample data here:
https://grafana.com/grafana/dashboards?orderBy=name&direction=asc

**Comment by jkremser** [comment]
related:

recently a new [plugin](https://master.book.kubebuilder.io/plugins/grafana-v1-alpha.html) has been added to kubebuilder for generating the sample grafana dashboards. The dashboard shows the common metrics that are exposed from the controller-runtime.

support for custom metrics:
- https://github.com/kubernetes-sigs/kubebuilder/pull/2858
