### ISSUE TITLE
🟢 Revisit github workflow pipelines

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#1297]
When switching to k8gb-lite, the makefiles, code structure, and three clusters for terratests are changed by default. Terratests have also been completely changed.  K8gb-lite has its own build test pipeline ready, but it needs to be plugged into k8gb. K8gb-lite has no upgrade tests, no release pipeline, helm-docs, helm-release pipeline. All these things need to be reconfigured to work with the new code.

**Comment by AugustasV** [comment]
@kuritka sounds good! I think dividing the issue into separate tasks would be a good approach as it can make it more manageable and easier to track progress.
