### ISSUE TITLE
🟢 Revisit documentation

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#1299]
A lot has changed in terms of documentation. First of all, the CRD has disappeared so you need to modify in the documentation. Also, everything is specified in ingress (including WRR, RR, Geo, FO), so this also needs to be mentioned in the documentation. The diagrams have also changed. 

- [WRR ingress configuration](https://github.com/k8gb-io/k8gb-lite/blob/main/terratest/test/resources/ingress_wrr.yaml#L6) must  be explained in documentation.

 - FO supports cluster [failover order](https://github.com/k8gb-io/k8gb-lite/blob/main/terratest/test/resources/ingress_fo3_ordered2.yaml#L6). Needs to be mentioned in documentation as well

- Makefiles has changed radically as well as target names, whole contributing needs to be changed. 

-  Another thing is Local Playground. First, we are implicitly working with three regions. Second local playground test is implemented in k8gb-lite terratests (dig + wget). We also added new strategies. Local playground needs to be extended for it.

**Comment by ytsarev** [comment]
Closing as discussed in https://github.com/k8gb-io/k8gb/issues/1301#issuecomment-2175388807
