### ISSUE TITLE
🟢 Release K8gb v1.0.0

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#1300]
If the Documentation, HelmCharts and pipelines are fixed. If all tests pass, we are ready for Release k8gb:v1.0.0!  

K8gb-lite resolves the following issues:  
- https://github.com/k8gb-io/k8gb/issues/1018
- https://github.com/k8gb-io/k8gb/issues/942
- https://github.com/k8gb-io/k8gb/issues/933
- https://github.com/k8gb-io/k8gb/issues/932
- https://github.com/k8gb-io/k8gb/issues/923
- https://github.com/k8gb-io/k8gb/issues/566
- https://github.com/k8gb-io/k8gb/issues/50
- [BUG] can't drop ingress when created from GSLB 
- _[BUG] ingress v1, v1beta1_ - must be tested 
- _[BUG] large number of reconciliation cycles_, optimize
- [FEATURE] install finalizer only for Infoblox
- https://github.com/k8gb-io/k8gb/issues/1044
- https://github.com/k8gb-io/k8gb/issues/878
- https://github.com/k8gb-io/coredns-crd-plugin/pull/45

**Comment by ytsarev** [comment]
Closing as discussed in https://github.com/k8gb-io/k8gb/issues/1301#issuecomment-2175388807
