### ISSUE TITLE
🟢 Replace the old k8gb code  with the new k8gb-lite code

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#1301]
This change happens in k8gb workspace.  Replace the old k8gb code with the new k8gb-lite code with the new k8gb-lite code.  The code must be compilable and the tests must be running.

**Comment by shane-davidson** [comment]
Hey @kuritka any news on the k8gb-lite code? I am looking at implementing k8gb but was hoping to use annotations on our existing ingress/gateway definitions (We also deploy a lot of external Helm charts so annotations would lower the cost of entry :) )

**Comment by kuritka** [comment]
Hi shane-davidson, thanks for your interest. We finally decided to decouple the GSLB from the Ingress resource. Please take a look here: https://github.com/k8gb-io/k8gb/pull/1557

**Comment by kuritka** [comment]
@ytsarev With great pain, I fear it will be better to close these Issues: 

#1297, #1298, #1299, #1300 , #1301

**Comment by ytsarev** [comment]
@kuritka 💯 totally agree, thanks a lot for the powerfuly k8gb-lite prototype and for being really open-minded to a different design approach 👍
