### ISSUE TITLE
"Additional property cloudflare is not allowed" appears when deploying Cloudflare integration

### ISSUE THREAD

**Issue by misawa3017** [k8gb-io/k8gb#1339]
<img width="925" alt="image" src="https://github.com/k8gb-io/k8gb/assets/5848317/862e041d-624e-42fa-8693-bc720f5ddfef">

**Comment by ytsarev** [comment]
@misawa3017 Thanks a lot for the report!

 it looks like we haven't made a release with cloudflare release support yet. The schema change is already there https://github.com/k8gb-io/k8gb/blob/master/chart/k8gb/values.schema.json#L33-L35 . You can try to install  chart from the repo to unblock yourself.

In the meantime, I will plan the release early next week.

**Comment by misawa3017** [comment]
thanks
