### ISSUE TITLE
scorecard pipeline is failing in `master` branch

### ISSUE THREAD

**Issue by ytsarev** [k8gb-io/k8gb#1566]
It's happening for a while, example https://github.com/k8gb-io/k8gb/actions/runs/9150847377

**Comment by ytsarev** [comment]
@jkremser as a supply chain master, do you see there some obvious fix? :)

**Comment by jkremser** [comment]
🤞 https://github.com/k8gb-io/k8gb/pull/1567

**Comment by ytsarev** [comment]
@jkremser, thanks a ton for the quick attempt! https://github.com/k8gb-io/k8gb/actions/runs/9157536246/job/25174078930 unfortunately, it still fails

**Comment by ytsarev** [comment]
breadcrumb https://github.com/ossf/scorecard-action/issues/997

**Comment by ytsarev** [comment]
```
2024/06/30 12:56:35 error signing scorecard json results: error signing payload: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: invalid key
```
which is matching the issue above
