### ISSUE TITLE
Detect and log NS servers A records propagation clash between two or more distinct k8gb pairs

### ISSUE THREAD

**Issue by ytsarev** [k8gb-io/k8gb#165]
*Problem statement*:

1. We have two separate k8gb pair installation with the similar configuration like `nonprod` and `prod` and the same geo tags , e.g. `eu` and `us`
2. If we have Gslb resource of the same name between two separate cluster pairs like `test-gslb` then the NS servers FQDNs would be constructed as `test-gslb-ns-eu.example.com` and `test-gslb-ns-us.example.com`
3. In this situation the NS server A records will be unintentionally shared between two distinct k8gb installation and response will be mixed containing IP addresses from both `nonprod` and `prod` clusters

*Possible solution*:

Automatically catch the NS server A records response inconsistency with own worker node lists and log the error

**Comment by kuritka** [comment]
from @ytsarev , consider to resolve by documentation

**Comment by kuritka** [comment]
![Screenshot 2021-09-21 at 16 44 46](https://user-images.githubusercontent.com/7195836/134192717-a03ce30f-a47d-40c5-a83e-0332586e1398.png)

 - The number of IPs can change during the runtime even on a valid configuration.  
 - Introducing new unique configuration field doesn't solve the problem
 - I was also considering guessing cluster subnets and single infoblox comment field on delegated zone. 

The correct solution is to create proper alerting on zone updates / (cloud) DNS  

see: 
 - [k8gb_infoblox_zone_updates_total](https://github.com/k8gb-io/k8gb/blob/master/docs/metrics.md#metrics-1) for infoblox
