### ISSUE TITLE
Add topology/location based load balancing strategy

### ISSUE THREAD

**Issue by donovanmuller** [k8gb-io/k8gb#244]
Add an additional [load balancing strategy](https://github.com/AbsaOSS/k8gb/blob/master/docs/index.md#load-balancing-strategies) that implements support for topology/location aware resolution of Ingress node IPs.

Where topology and location refer to:

### Topology

Resolve Ingress node IPs for _internal_ (workloads running in the same cluster/availability zone/region as k8gb) clients in the same or closest network/VPC, datacenter or region. I.e. Ensure internal clients are always resolved to the most optimal (as determined by network topology or location) Ingress node for the lowest possible latency etc.

### Location

Resolve Ingress node IPs for _external_ clients based on geographic location. I.e. Ensure external clients are always resolved to the _geographically closest_ Ingress for the lowest possible latency etc.

**Comment by raffaelespazzoli** [comment]
here one can find an example of a free geoip database: https://lite.ip2location.com/database/ip-country-region-city-latitude-longitude-zipcode
I didn't do much research, there could be better sources.

**Comment by k0da** [comment]
All required pieces are merged, closing
