### ISSUE TITLE
Create separate README.md file for k8gb helm chart

### ISSUE THREAD

**Issue by somaritane** [k8gb-io/k8gb#359]
Current documentation for k8gb helm chart is linked to root README.md from k8gb repo.
It contains information that is not specific to helm chart.
It would be better to author separate lightweight README.md for k8gb chart with short description and reference to main project repo. It would also describe helm chart parameters and contain only helm-specific usage examples.

**Comment by somaritane** [comment]
https://github.com/norwoodj/helm-docs or similar can be used to auto-generate values table in README.

**Comment by jkremser** [comment]
Adding some ascii banner to the https://github.com/k8gb-io/k8gb/blob/master/chart/k8gb/templates/NOTES.txt would be cool, something like 
```
 _    ___        _
| | _( _ )  __ _| |__
| |/ / _ \ / _` | '_ \
|   < (_) | (_| | |_) |
|_|\_\___/ \__, |_.__/
           |___/
```
\+ possibly collors alligned w/ the k8gb.io site/logo

The stuff in NOTES.txt is displayed after helm install or upgrade - https://helm.sh/docs/chart_template_guide/notes_files/
