### ISSUE TITLE
[opensihft-support] global record not populated 

### ISSUE THREAD

**Issue by raffaelespazzoli** [k8gb-io/k8gb#424]
k8gb looks for the `status.loadbalancer.ingress.hostname` field to determine how to populate the global dns record. this corresponds to the `status.ingress.routeCanonicalHostname` field in the corresponding route.
This hostname is actually an wildcard entry and cannot be resolved (or at least it cannot be resolved when running on AWS). As a result k8gb is unable to populate the global record.
A fix to this solution would be to make the wildcard name resolvable.
A more immediate but inelegant workaround would be for k8gb to try to resolve `anything.{status.ingress.routeCanonicalHostname}`

**Comment by ytsarev** [comment]
I assume it is solved with https://www.redhat.com/en/blog/global-load-balancing-red-hat-openshift-k8gb implementation. Please reopen if it is still valid
