### ISSUE TITLE
Create governance document

### ISSUE THREAD

**Issue by ytsarev** [k8gb-io/k8gb#436]
As part of CNCF onboarding at https://github.com/cncf/toc/issues/628  we need to adopt https://github.com/opengovernance/opengovernance.dev

**Comment by ytsarev** [comment]
Interesting conversation on Open Governance topic https://www.tfir.io/open-source-open-governance-dirk-hohndel-swapnil-bhartiya/

**Comment by somaritane** [comment]
Fixed by #458
