### ISSUE TITLE
Consider and implement the desired level of the Operator Maturity Model

### ISSUE THREAD

**Issue by donovanmuller** [k8gb-io/k8gb#51]
Given the five phases of the [Operator Maturity Model](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level.png): 

1. Basic Install
2. Seamless Upgrades
3. Full Lifecycle
4. Deep Insights
5. Auto Pilot

Consider all phases and implement the necessary tasks to achieve the desired maturity phase.

**Comment by somaritane** [comment]
Currently, we're at level 2 (Seamless Upgrades), and I'm not sure we want to move up the ladder in the nearest future unless we have a requested from the community. I suggest closing this one for now.

**Comment by ytsarev** [comment]
We do not have a demand to use this module, let's close
