### ISSUE TITLE
Enable DCO for all of k8gb (CNCF requirement)

### ISSUE THREAD

**Issue by caniszczyk** [k8gb-io/k8gb#523]
https://github.com/organizations/k8gb-io/settings/installations/17617274

**Comment by ytsarev** [comment]
@somaritane @caniszczyk so looks like it's done and we can close this one?

**Comment by somaritane** [comment]
@ytsarev , yep, I think DCO check at #524 proves it

**Comment by ytsarev** [comment]
@somaritane well, #524 does not fully prove it as DCO was already enabled specifically for k8gb repo. But I think we are good here anyway
