### ISSUE TITLE
Make LeaderElection accessible

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#526]
The LeaderElection controller property is hardcoded. Currently set to false. 

 - Make LeaderElection accessible via environment variable (and if necessary, provide another implementation to make the leader election work)
 - Provide tests to prove that the leaderelection mechanism works
 
```go
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:             runtimescheme,
		MetricsBindAddress: config.MetricsAddress,
		Port:               9443,
		LeaderElection:     false, // <---- config.LeaderElection
		LeaderElectionID:   "8020e9ff.absa.oss",
	})
```

**Comment by ytsarev** [comment]
https://github.com/elastic/cloud-on-k8s/pull/3632#issuecomment-676032888 might relevant

**Comment by somaritane** [comment]
Parking this one.
