### ISSUE TITLE
Feature Request/Idea: Extend registration to ISTIO and Virtual Services

### ISSUE THREAD

**Issue by ssurovich** [k8gb-io/k8gb#552]
K8GB works great for standard Ingress rules, so I was curious if the team has considered extending the support beyond only Ingress objects - like VirtualServices in ISTIO?

From a high-level, I believe it should be as "simple" as extending the annotations to support ISTIO VirtualServices to create the DNS records for mesh based applications?

**Comment by k0da** [comment]
@ssurovich we have GatewayAPI support on the list, that will potentially will open a door to any other resources

**Comment by ssurovich** [comment]
Hi @k0da - Sounds very intriguing - looking forward to that support at some point.    I appreciate the quick reply!

**Comment by abaguas** [comment]
What are the current plans for this feature?
I would be interested to try out k8gb but we configure ingress using `gateways.networking.istio.io` resources.

Having this features would open the door to all users using the most popular service mesh in the market.

**Comment by ytsarev** [comment]
Hi @abaguas , thanks a lot for your feedback, this feature is still in the backlog. We will try to prioritize it according to the community's interest!

**Comment by ytsarev** [comment]
Hey @RafalMaleska ! It's nice to hear from you! 

Our initial thinking was that Gateway API(aka ingress v2) support would go first, and during the implementation, we could figure out how to build the integration with other resources like Istio Gateways. It hasn't happened yet, so I have no strong preference for implementation ordering. 

My high-level idea is to detach Ingress from Gslb spec and be able to reference arbitrary Ingress as the first step. Then we could potentially reference other resource types like `gateways.networking.istio.io` or `gateway.networking.k8s.io` or anything else semantically matching. 

Are you keen to share some details of your setup and potentially test the integration in the future?

That would seriously help with the feature implementation 👍
