### ISSUE TITLE
Occasional reconciler error

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#566]
`k8gb_gslb_error_total` metric revealed , an unexpected error generated inside the controller runtime. From my observation, the error is not critical to the functioning of k8gb, it just messes up the metrics.
Find out what in k8gb is causing this error and make the necessary changes. 

_the error occurs very little and appears after a while of running on localhosts_

```shell
+ k8gb-56c6795669-8l4kn › k8gb
k8gb-56c6795669-8l4kn k8gb 2021-08-19T13:31:30Z ERR workspace/controllers/logging/logr.go:60 > gslb: Reconciler error {"name":"test-gslb-failover","namespace":"test-gslb","reconciler group":"k8gb.absa.oss","reconciler kind":"Gslb"} error="Operation cannot be fulfilled on gslbs.k8gb.absa.oss \"test-gslb-failover\": the object has been modified; please apply your changes to the latest version and try again"
k8gb-56c6795669-8l4kn k8gb 2021-08-19T13:31:44Z ERR workspace/controllers/logging/logr.go:60 > gslb: Reconciler error {"name":"test-gslb","namespace":"test-gslb","reconciler group":"k8gb.absa.oss","reconciler kind":"Gslb"} error="Operation cannot be fulfilled on gslbs.k8gb.absa.oss \"test-gslb\": the object has been modified; please apply your changes to the latest version and try again"
k8gb-56c6795669-8l4kn k8gb 2021-08-19T13:31:44Z ERR workspace/controllers/logging/logr.go:60 > gslb: Reconciler error {"name":"test-gslb","namespace":"test-gslb","reconciler group":"k8gb.absa.oss","reconciler kind":"Gslb"} error="Operation cannot be fulfilled on gslbs.k8gb.absa.oss \"test-gslb\": the object has been modified; please apply your changes to the latest version and try again"
```

**Comment by somaritane** [comment]
@kuritka is this still the issue?

**Comment by kuritka** [comment]
Hi @somaritane,  just checked locally. Yes, the Reconciler error still ocurs.

**Comment by ytsarev** [comment]
@kuritka it very frequent situation for k8s based projects. Please see how it was handled by crossplane runtime https://github.com/crossplane/crossplane-runtime/pull/498 . TL;DR : let's just move such events to debug log level of minimal importance

**Comment by ytsarev** [comment]
@kuritka I think it's not the case anymore and will close the issue. Feel free to reopen if it is still valid
