### ISSUE TITLE
Add k8gb delivery scenario to podtato head

### ISSUE THREAD

**Issue by ytsarev** [k8gb-io/k8gb#643]
CNCF App Delivery SIG maintains a nice demo app of https://github.com/podtato-head/podtato-head

Extending [delivery scenarios](https://github.com/podtato-head/podtato-head#delivery-scenarios) with k8gb example will be beneficial for the project and visibility

**Comment by AugustasV** [comment]
Interested to work on it from next week.

**Comment by ytsarev** [comment]
@AugustasV amazing!

**Comment by AugustasV** [comment]
Where I should start, lost littlebit. I will try to create Helm delivery scenario, locally I am able to deploy using deploy-full-local-setup script.

**Comment by ytsarev** [comment]
no demand for this one at the moment. Closing
