### ISSUE TITLE
Revisit the project linting scope

### ISSUE THREAD

**Issue by somaritane** [k8gb-io/k8gb#775]
According to the discussion in https://github.com/k8gb-io/k8gb/pull/774#discussion_r757676464, not all project paths are covered by our linting workflows/tasks.

**Comment by kuritka** [comment]
fount this: 
 - https://github.com/golangci/golangci-lint/issues/828
 
 Once `go.mod` is added to subfolder, it is skipped by local linter.

**Comment by ytsarev** [comment]
linting was tweaked multiple times, assuming this one solved
