### ISSUE TITLE
Test implemented LB strategies for more than 2 cluster scenario 

### ISSUE THREAD

**Issue by ytsarev** [k8gb-io/k8gb#78]
Most of the current use cases, automated tests and functional test scenarios were performed in context of 2 clusters only as it is most common and easier to test setup.

Meanwhile we need to be ready and test for >2 scenario cluster scenario.

This series of testing can reveal potential edge cases in current LB strategies implementation and can lead to LB logic extension and handling of >2 number of clusters

**Comment by somaritane** [comment]
https://github.com/k8gb-io/k8gb/pull/815/

**Comment by somaritane** [comment]
@jkremser let's revisit the case and make a decision if we support failover for >2 cluster cases

**Comment by ytsarev** [comment]
The strategies work with > 3 clusters after https://github.com/k8gb-io/k8gb/pull/1705 , thanks to @abaguas !
