### ISSUE TITLE
Check if incoming code is gofmt-ed 

### ISSUE THREAD

**Issue by jkremser** [k8gb-io/k8gb#817]
Currently neither the `golangci-lint run` nor the `gokart scan --globalsTainted --verbose` do catch some things that `gofmt -w -s .` does to code.
We can do `gofmt -l .` that lists all the files that are not aligned w/ the gofmt (~something like a dry run) and check if the output is empty.

Currently it's complaining about terrratest:

```
 gofmt -l .
terratest/test/init.go
terratest/test/k8gb_abstract_full_roundrobin_test.go
terratest/test/k8gb_basic_app_test.go
terratest/test/k8gb_failover_playground_test.go
terratest/test/k8gb_full_failover_test.go
terratest/test/k8gb_full_roundrobin_test.go
terratest/test/k8gb_ingress_annotation_failover_test.go
terratest/test/k8gb_ingress_annotation_rr_test.go
terratest/test/k8gb_lifecycle_test.go
terratest/test/k8gb_split_failover_test.go
```
I've checked couple of those and it's my work, perhaps I will setup also some pre-commit hook w/ gofmt. We could have this also in the repo itself, but it might be [controversial](https://stackoverflow.com/a/54281447).

note:
gofmt has an option `-s` that can simplify the code and these wannabe modifications are not listed w/ `-l`, but these can be checked by `gofmt -s -d .` (again if the output is empty, we are good)

**Comment by jkremser** [comment]
ah, I've completely missed this https://github.com/k8gb-io/k8gb/blob/master/.golangci.yaml#L43 so it looks like it's on purpose. I wonder why though.

**Comment by kuritka** [comment]
@jkremser  _Goimports does everything that gofmt does. Additionally it adds missing imports and removes unreferenced imports_ , regarding [this article](https://medium.com/wesionary-team/introduction-to-linters-in-go-and-know-about-golangci-lint-6486fb2864b3).

I found one issue  with enabled ` - gofmt` and :
```yaml
  gofmt:
    # gofmt -s
    simplify: true
```

The question is, if we must keep both - goimports + gofmt or goimports can be configured to replace `gofmt -s`.

**Comment by jkremser** [comment]
I see, so somehow the `golangci-lint run` is not being run against the terratest module.

I'd probably whitelisted the gofmt, they don't fight against each other and can be run both (also the output is not duplicated), wdyt?

right now, it reports 

```
main.go:41: File is not `goimports`-ed (goimports)
	version       =  "development"
```
which is kind of misleading

should be (if gofmt is enabled)
```
main.go:41: File is not `gofmt`-ed with `-s` (gofmt)
	version       =  "development"
```

**Comment by jkremser** [comment]
wrt terratest
`cd terratest/ && golangci-lint run` ... works

**Comment by ytsarev** [comment]
closing as solved, we can reopen if linting brings troubles again
