### ISSUE TITLE
Deploying locally is failing, resources not created

### ISSUE THREAD

**Issue by AugustasV** [k8gb-io/k8gb#828]
Tried to deploy locally by executing command `make deploy-full-local-setup` Got this error. Tried to remove unnecessary containers.

```ERRO[0003] Failed Cluster Start: Failed to start server k3d-test-gslb1-server-0: Node k3d-test-gslb1-server-0 failed to get ready: error waiting for log line `k3s is up and running` from node 'k3d-test-gslb1-server-0': stopped returning log lines 
ERRO[0003] Failed to create cluster >>> Rolling Back    
INFO[0003] Deleting cluster 'test-gslb1'                
INFO[0003] Deleting image volume 'k3d-test-gslb1-images' 
FATA[0003] Cluster creation FAILED, all changes have been rolled back! 
make[1]: *** [Makefile:159: create-local-cluster] Error 1
make[1]: Leaving directory '/home/namai/Documents/k8gb'
make[1]: Entering directory '/home/namai/Documents/k8gb'```

What steps I should take to find the cause? 
OS: Debian 11 "Bullseye"
Go 17.6.1
Docker 20.10.5

**Comment by kuritka** [comment]
Hi @AugustasV , could you try `make reset`? The command remove clusters and redeploy. Also, please make sure you have k3d@5.2.2 handling case you delete clusters that have not yet been created. 

if that doesn't help, try creating the cluster manually with the `-verbose` argument
```
k3d cluster create -c k3d/test-gslb1.yaml --verbose
```

**Comment by AugustasV** [comment]
Thank you for tips, I noticed that somehow new container called kublr, who didn't let create new nod even using k3d command. When I stoped and deleted that container, with k3d command all went smooth and node was created.
```
INFO[0020] Cluster 'test-gslb1' created successfully!   
DEBU[0020] Updating default kubeconfig with a new context for cluster test-gslb1 
DEBU[0020] Setting new current-context 'k3d-test-gslb1' 
DEBU[0020] Wrote kubeconfig to '/home/namai/.kube/config' 
INFO[0020] You can now use it like this:                
kubectl cluster-info
```
But terratest results failing, and round-robin tests failing
```
    extensions.go:235: killing Instance: k3d-test-gslb2:k8gb-test-bmgcyi
TestFullFailover 2022-01-14T21:56:28+02:00 client.go:42: Configuring Kubernetes client using config file /home/namai/.kube/config with context k3d-test-gslb2
    extensions.go:235: killing Instance: k3d-test-gslb1:k8gb-test-w0g9tt
TestFullFailover 2022-01-14T21:56:28+02:00 client.go:42: Configuring Kubernetes client using config file /home/namai/.kube/config with context k3d-test-gslb1
--- FAIL: TestFullFailover (441.28s)
    --- PASS: TestFullFailover/failover_on_two_concurrent_clusters_with_podinfo_running (3.04s)
    --- FAIL: TestFullFailover/kill_podinfo_on_the_second_cluster (105.48s)
    --- PASS: TestFullFailover/kill_podinfo_on_the_first_cluster (0.20s)
    --- FAIL: TestFullFailover/start_podinfo_on_the_second_cluster (109.56s)
    --- FAIL: TestFullFailover/start_podinfo_on_the_first_cluster (106.90s)
FAIL
exit status 1
FAIL    k8gbterratest/test      441.297s
```

**Comment by kuritka** [comment]
@AugustasV , I created a separate issue for your last message (#834).

Resolved regarding the complications mentioned in the issue header.

/closed
