### ISSUE TITLE
Fix FOSSA license scan issue(s)

### ISSUE THREAD

**Issue by somaritane** [k8gb-io/k8gb#880]
According to FOSSA license scan k8gb.io has two unlicensed dependencies: https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fk8gb-io%2Fk8gb/refs/branch/master/8820bba2d07a9c13c233e725c17cf06e4aeaf696

**Comment by ytsarev** [comment]
FOSSA is green on `master` https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fk8gb-io%2Fk8gb/refs/branch/master/6b253b0dfd0a9cd12d363ad2020a79c273c31838/preview
