### ISSUE TITLE
Cloudflare GSLB support

### ISSUE THREAD

**Issue by all4innov** [k8gb-io/k8gb#884]
Is it or any plan to support Cloudflare GSLB ?

**Comment by somaritane** [comment]
@all4innov, thank you for your interest in k8gb project!
Can you please elaborate on your case a bit more? 
Is it about the support of Cloudflare DNS as one of k8gb EdgeDNS servers?
Or is it about integration with the Cloudflare LoadBalancing solution?

**Comment by ytsarev** [comment]
That might be a good and easy thing to add as we are using external-dns within the project. The only thing we need is testing Cloudflare account.

**Comment by somaritane** [comment]
https://github.com/kubernetes-sigs/external-dns/tree/master/provider/cloudflare
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md

**Comment by cfifua** [comment]
I am interested in this feature a lot.
So far we 2 external DNS. 

The first one is configuring the Cloudflare DNS records, based on Ingress object annotations: external-dns.alpha.kubernetes.io/hostname
