### ISSUE TITLE
Terratest: identify ImagePullBackOff and exit ASAP with proper message

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#898]
Terratest often uses functions like `k8s.WaitUntil...`, e.g.: `WaitUntilNumPodsCreatedE(...)`. If POD cannot be started because of `ImagePullBackOff`, terratest waits unnecessarily until a certain number of retries have elapsed. Apart from the fact that terratest runs unnecessarily even though the error is clear, the developer then has to spend time looking for the error etc.. 

- Consider:
  - if an optimization would be appropriate, exit immediately and provide an understandable errorMessage 
  - if it makes sense to do the same for `CrashLoopBackOff`.
  - This behavior may be configurable.

**Comment by ytsarev** [comment]
stale, closing
