### ISSUE TITLE
intermittent failure of container image build

### ISSUE THREAD

**Issue by jkremser** [k8gb-io/k8gb#904]
Sometimes goreleaser is not able to build the multiarch image and if it fails for 1 platform, it fails the whole build with this cryptic issue:

https://github.com/k8gb-io/k8gb/runs/6816387426?check_suite_focus=true#step:4:55

```
release failed after 264.80serror=failed to build absaoss/k8gb:v0.9.0-c1f7cc7-amd64: exit status 1: Sending build context to Docker daemon  33.97MB
...
WARNING: Pulled image with specified platform (linux/amd64), but the resulting image's configured platform (linux/arm64) does not match.
...
failed to get destination image "sha256:367aa1e9d4caebc5c2700bb80d68a1e148a37a4b886a7b721b5a6fbccd1b7e5f": image with reference sha256:367aa1e9d4caebc5c2700bb80d68a1e148a37a4b886a7b721b5a6fbccd1b7e5f was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64
```

Restarting the build helps, second attempt went just fine

**Comment by somaritane** [comment]
@jkremser did #916 fix this issue, can we close it?

**Comment by jkremser** [comment]
nope, it's still there, I saw the issue couple of days ago

**Comment by jkremser** [comment]
actually it's been 27 days, but it's still there https://github.com/k8gb-io/k8gb/actions/runs/3046089118/jobs/4908461364

**Comment by jkremser** [comment]
there we go https://github.com/k8gb-io/k8gb/actions/runs/3266320723/jobs/5369895011#step:4:56

**Comment by ytsarev** [comment]
stale, we didn't see this one for a while, closing
