### ISSUE TITLE
Support multiple edgeDNS types in parallel to enable hybrid and multi-cloud scenarios

### ISSUE THREAD

**Issue by ytsarev** [k8gb-io/k8gb#919]
**Problem statement**

Currently, k8gb is [limited](https://github.com/k8gb-io/k8gb/blob/master/controllers/providers/dns/factory.go#L46-L55) to work only with a single specific edgeDNS type and tested to work exclusively in a single DNS environment.
It limits the ability of operating in a hybrid scenario, e.g.

* deploying k8gb in parallel to on-prem clusters with Infoblox and to AWS with Route53 as edgeDNS and orchestrating DNS zone delegation to k8gb instances between cloud and on-prem
* deploying k8gb in parallel to multiple clouds like AWS/Azure/GCP and orchestrating DNS zone delegation to k8gb instances between multiple clouds

**Possible solution**

* Enable multiple edgeDNStypes handling
* Test it in hybrid/multiple cloud scenario
* We already have some configuration logic semantically prepared to handle this case https://github.com/k8gb-io/k8gb/blame/master/controllers/depresolver/depresolver.go#L75

**Comment by somaritane** [comment]
@ytsarev to my understanding, with one k8gb instance, deployed to environment A and configured to use that environment-specific EdgeDNS (e.g. AWS and Route53), and then another k8gb instance deployed on environment B with specific EdgeDNS (e.g. on-prem with Infoblox) - then we got this scenario covered.

**Comment by somaritane** [comment]
Or did you mean some complex scenario, when for example we have workloads exposed with different zones in the cluster that need to be resolved using different EdgeDNS providers?

**Comment by ewassef** [comment]
How about having multiple HostedZones ( Route53 example) and allowing K8GB to manage those? It seems like only a single host can be configured in the operator at a time

**Comment by ytsarev** [comment]
@ewassef good point, we can both relax the filter to handle multiple zones and also orchestrate multiple external-dns instances to handle multiple DNS environments/clouds in parallel

**Comment by ytsarev** [comment]
stale, we manage a single edge DNS zone, meanwhile workloads can be placed in a multi-cloud manner. Closing.
