### ISSUE TITLE
Extend gslb object print columns with HOSTS

### ISSUE THREAD

**Issue by somaritane** [k8gb-io/k8gb#922]
For the sake of readability, it would be good to extend `gslb` CRD print columns with `HOSTS` column,
similar to the one displayed for an ingress object in `kubectl` output, e.g:
```
❯ kubectl get gslb -n test-gslb test-gslb
NAME        STRATEGY    GEOTAG   HOSTS
test-gslb   roundRobin  eu       notfound.k8gb-test-nonprod.gslb.test.com,unhealthy.k8gb-test-nonprod.gslb.test.com,roundrobin.k8gb-test-nonprod.gslb.test.com
```

**Comment by k0da** [comment]
Isn't it done by @ytsarev already?

**Comment by somaritane** [comment]
@k0da from what I see, it has been done for `STRATEGY` and `GEOTAG` only:
https://github.com/k8gb-io/k8gb/blob/master/api/v1beta1/gslb_types.go#L69-L70

**Comment by k0da** [comment]
@somaritane right.
https://github.com/k8gb-io/k8gb/pull/425#issuecomment-812684552

**Comment by jkremser** [comment]
btw. the print column can also have a priority number assigned to it so that those with some high values are not displayed by default (i don't know the threshold from top of my head), but one can still show them by `-o wide`.

**Comment by jkremser** [comment]
the closest I was able to get with the standard print column approach + simple json path was this

```yaml
    - jsonPath: .spec.ingress.rules[*].host
      name: hosts
      type: string
```

```bash
get gslbs.k8gb.absa.oss test-gslb-failover
NAME                 STRATEGY   GEOTAG   HOSTS
test-gslb-failover   failover   us       failover.cloud.example.com
```

However, there were more hosts present on the gslb, it displays only one.

```bash
k get gslb test-gslb-failover -ntest-gslb -o=jsonpath="{.spec.ingress.rules[*].host}"
failover.cloud.example.com foo.bar blahbla.com
```

or 

```
k get gslb test-gslb-failover -ntest-gslb -o=jsonpath="{range .spec.ingress.rules[*]}{.host},{end}"
failover.cloud.example.com,foo.bar,blahbla.com
```

Standard approach would be to duplicate some stuff from `.spec` under `.status` that will be consumed by the printer columns simple jsonpath. Because these doesn't support ranges or any other form of iteration.

**Comment by somaritane** [comment]
Interesting, I wonder how ingress printer does that?
because I don't see hosts duplicated in status for ingress, but it displays all hostnames for simple k get

**Comment by jkremser** [comment]
@somaritane good question, but I don't have an answer ;) I _think_ that Ingress is treat differently than CRDs (no CRD manifest, perhaps some better love in kubectl)
