### ISSUE TITLE
Add support for Linode

### ISSUE THREAD

**Issue by somaritane** [k8gb-io/k8gb#928]
Explore the possibility for k8gb integration with Linode as a cloud provider:
Linode @ ExternalDNS: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/linode.md
https://www.linode.com/community/questions/17956/how-do-you-use-external-dns-in-kubernetes-with-linode-domains
Linode LKE: https://www.linode.com/docs/products/compute/kubernetes/
Linode DNS: https://www.linode.com/docs/guides/dns-manager/
https://www.linode.com/docs/api/domains/#domain-record-create

**Comment by ytsarev** [comment]
There is currently not demand from community, we can reopen if needed
