### ISSUE TITLE
Cloudflare EdgeDNS support

### ISSUE THREAD

**Issue by der-ali** [k8gb-io/k8gb#944]
Is cloudflare supported as one of k8gb EdgeDNS servers ?

**Comment by ytsarev** [comment]
We didn't test it before but looking at https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md it looks promising.

We need to double check NS record creation support in Cloudflare.

@der-ali are you willing to test the setup assuming we provide you the config? Non of the maintainers has Cloudlfare access AFAIK, so testing on your side would be extremely valueable

**Comment by der-ali** [comment]
Hi @ytsarev, gladly! 
We are currently planning to build the second-site. I will inform as soon as we are ready for testing.

**Comment by ytsarev** [comment]
@der-ali amazing, thanks! I will try to prepare associated configs in the meantime

**Comment by ytsarev** [comment]
@der-ali we discussed this issue at today's k8gb community meeting. We are trying to evaluate if the associated external-dns cloudflare provider correctly supports "NS" record creation. Is possible that you can test Cloudflare external-dns part in isolation following https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md and creating NS record as expected result? Thank you so much in advance

**Comment by ytsarev** [comment]
Fixed in https://github.com/k8gb-io/k8gb/pull/1278
