### ISSUE TITLE
node@12 has been deprecated warnings

### ISSUE THREAD

**Issue by jkremser** [k8gb-io/k8gb#965]
The GH actions that use node12 produce these warnings in our pipeline:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: fkirc/skip-duplicate-actions
```

Also similarly `set-output` was deprecated and this should be used instead: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable

So once/if those actions are updated to 16 or later we should also update those versions to get rid of those warnings.
Namely it's:
- `actions/checkout` (3.1.0 should be ok)
- `fkirc/skip-duplicate-actions` (master is on [16](https://github.com/fkirc/skip-duplicate-actions/blob/master/package.json#L27) so probably 5.2.0 should be ok)
- `actions/setup-go` (https://github.com/actions/setup-go/blob/main/package.json#L37 anything 3.x.x should be ok)
- `docker/login-action` (2.1.0 should be ok)

**Comment by kuritka** [comment]
Also found that issue in [coredns-crd-plugin](https://github.com/k8gb-io/coredns-crd-plugin/actions/runs/3234403056).
