### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by hernanpl** [k8gb-io/k8gb#970]
This repo is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam). I'm bringing to your attention the checklist from the official [CLOMonitor page for K8GB](https://clomonitor.io/projects/cncf/k8gb) -- it refreshes every hour, so it should be up-to-date.

### Summary

**Repository**: k8gb
**URL**: https://github.com/k8gb-io/k8gb
**Checks sets**:  `COMMUNITY` + `CODE`
**Score**: 84

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  93%  |
|  License  |  100%  |
|  Best Practices  |  85%  |
|  Security  |  75%  |
|  Legal  |  0%  |

### Documentation [93%]

  - [x] Adopters ([_docs_](https://clomonitor.io/docs/topics/checks/#adopters))
  - [x] [Changelog](https://github.com/k8gb-io/k8gb/blob/master/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Code of conduct](https://github.com/k8gb-io/k8gb/blob/master/code-of-conduct.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#code_of_conduct))
  - [x] [Contributing](https://github.com/k8gb-io/k8gb/blob/master/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Governance](https://github.com/k8gb-io/k8gb/blob/master/GOVERNANCE.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#governance))
  - [x] [Maintainers](https://github.com/k8gb-io/k8gb/blob/master/CODEOWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/k8gb-io/k8gb/blob/master/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  - [x] Roadmap ([_docs_](https://clomonitor.io/docs/topics/checks/#roadmap))
  - [x] [Website](https://www.k8gb.io) ([_docs_](https://clomonitor.io/docs/topics/checks/#website))
  
### License [100%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [x] [License scanning](https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fk8gb-io%2Fk8gb?ref=badge_shield) ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [85%]

  - [x] Analytics ([_docs_](https://clomonitor.io/docs/topics/checks/#analytics))
  - [x] [Artifact Hub badge](https://artifacthub.io/packages/search?repo=k8gb) ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Community meeting ([_docs_](https://clomonitor.io/docs/topics/checks/#community_meeting))
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] Github discussions ([_docs_](https://clomonitor.io/docs/topics/checks/#github_discussions)) `EXEMPT`
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/4866) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] Recent release ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  - [x] Slack precense ([_docs_](https://clomonitor.io/docs/topics/checks/#slack_presence))
  
### Security [75%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/k8gb-io/k8gb/blob/master/SECURITY.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [x] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
### Legal [0%]

  - [x] Trademark disclaimer ([_docs_](https://clomonitor.io/docs/topics/checks/#trademark_disclaimer))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by ytsarev** [comment]
Hi @hernanpl, thanks a lot for creating this issue for us.

As a part of Security Slam, we heavily attacked the Security section of CLO monitor today.

* We [implemented](https://github.com/k8gb-io/k8gb/pull/966) first signed release with SBOM https://github.com/k8gb-io/k8gb/releases/tag/v0.10.0 
* Fully addressed token permissions and the rest of the stepsecurity recommendations in https://github.com/k8gb-io/k8gb/pull/990


Concerns:
* Apparently Signed releases check expects the last 5 releases to be signed, but we just implemented associated mechanisms so we have only 1 latest signed release. The pipelines are configured to automatically sign all future releases but we will not be generating 4 more releases before the Security Slam deadline. Is there a chance to give us a full score here given the context?
<img width="511" alt="image" src="https://user-images.githubusercontent.com/518532/196535811-4fd35630-0438-43f8-b21b-606c8c1ad20e.png">
* Token permissions are fully implemented but the associated check is still red ( meanwhile CLOMonitor claims that it was updated 20 minutes ago way after the associated fix)
<img width="696" alt="image" src="https://user-images.githubusercontent.com/518532/196536489-a164f599-f64e-44cd-8b27-91369106e604.png">
It seems that something is wrong with the check as all recommendations are already in the main branch

Could you please help with addressing concerns? I believe we made good progress today and it deserves some more monitor scores :)

**Comment by eddie-knight** [comment]
> We https://github.com/k8gb-io/k8gb/pull/966 first signed release with SBOM

This is perfect for the security slam, where the metric is just CLOMonitor's `score > 1` :+1: For your OpenSSF badge the score will be tallied more comprehensively, but IMHO that's out of scope at the moment

**Comment by eddie-knight** [comment]
> It seems that something is wrong with the check as all recommendations are already in the main branch

So there are two things happening here. 

The first one is that `actions: write` is currently an instant failure _anywhere_ in a workflow. So we'll either need to remove that, or raise this as a suggested change in https://github.com/ossf/scorecard/issues/2338

Secondly... I noticed that a few files don't have any permissions applied. These are also instant failures for the check.

- .github/workflows/terrascan.yaml
- .github/workflows/terratest-more-clusters.yaml
- .github/workflows/terratest.yaml
- .github/workflows/upgrade-testing.yaml

**Comment by ytsarev** [comment]
thanks a lot for the catch, I had an illusion that the secure-workflows tooling automatically fixed all issues for me :)

Created additional https://github.com/k8gb-io/k8gb/pull/1002

**Comment by ytsarev** [comment]
Just to not here for future reference. 

The way to locally get detailed token permissions feedback
```
scorecard --repo k8gb-io/k8gb --checks Token-Permissions --show-details
```

**Comment by ytsarev** [comment]
Good progress with overall local result:

```
clomonitor-linter --path ~/upstream/k8gb --url https://github.com/k8gb-io/k8gb

CLOMonitor linter results

Repository information

╭────────────┬─────────────────────────────────╮
│ Local path ┆ /Users/xnull/upstream/k8gb      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Remote url ┆ https://github.com/k8gb-io/k8gb │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Check sets ┆ [Code, Community]               │
╰────────────┴─────────────────────────────────╯

Score summary

╭────────────────┬───────╮
│     Section    ┆ Score │
╞════════════════╪═══════╡
│ Global         ┆   98  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ Documentation  ┆  100  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ License        ┆  100  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ Best practices ┆  100  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ Security       ┆   90  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ Legal          ┆  100  │
╰────────────────┴───────╯

Checks summary

╭──────────────────────────────────────┬────────────╮
│                 Check                ┆   Passed   │
╞══════════════════════════════════════╪════════════╡
│ Documentation / Adopters             ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Changelog            ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Code of conduct      ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Contributing         ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Governance           ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Maintainers          ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Readme               ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Roadmap              ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Documentation / Website              ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ License                              ┆ Apache-2.0 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ License / Approved                   ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ License / Scanning                   ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / Analytics           ┆     GA4    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / Artifact Hub badge  ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / CLA                 ┆   Exempt   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / Community meeting   ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / DCO                 ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / GitHub discussions  ┆   Exempt   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / OpenSSF (CII) badge ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / Recent release      ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Best practices / Slack presence      ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Binary artifacts          ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Code review               ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Dangerous workflow        ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Dependency update tool    ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Maintained                ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / SBOM                      ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Security policy           ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Signed release            ┆      ✓     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Security / Token permissions         ┆      ✗     │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Legal / Trademark disclaimer         ┆      ✓     │
╰──────────────────────────────────────┴────────────╯

✓ Succeeded with a global score of 98
```

**Comment by ytsarev** [comment]
@eddie-knight https://github.com/k8gb-io/k8gb/pull/1002 was merged, I also reported https://github.com/ossf/scorecard/issues/2338#issuecomment-1283729068

Is there anything more we can do? Really keen to score 100 :)

**Comment by eddie-knight** [comment]
@ytsarev I pinged the OpenSSF Scorecard channel discussing the release, need to get that cut before it can be propogated out to CLOMonitor

**Comment by ytsarev** [comment]
Thanks a lot @eddie-knight !

Just to be sure that we are good with the evaluation, I've built the scorecard from the `main` branch and it looks good!

```
./scorecard --repo k8gb-io/k8gb --checks Token-Permissions --show-details
Starting [Token-Permissions]
Finished [Token-Permissions]

RESULTS
-------
Aggregate score: 10.0 / 10
```

Thank you so much for the associated PR https://github.com/ossf/scorecard/pull/2367 !

**Comment by ytsarev** [comment]
We are all green at https://clomonitor.io/projects/cncf/k8gb !

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/518532/199801546-a16a276d-19ed-45fe-9813-88b9aa65c923.png">

Closing this one :)
